// ═══════════════════════════════════════════════════════════════════
// BANCO DE PREGUNTAS DWES — Desarrollo Web en Entorno Servidor
// Criterio de selección: se priorizan conceptos teóricos examinables
// en tipo test: definiciones, diferencias, comandos, comportamientos,
// errores de seguridad, métodos de clases y funciones PHP/Laravel/REST.
// ═══════════════════════════════════════════════════════════════════

const BANCO = {

  // ─────────────────────────────────────────────────────────
  // UF1 — INTRODUCCIÓN AL LADO SERVIDOR
  // ─────────────────────────────────────────────────────────
  UF1: [
    { tema:'UF1', p:'¿Qué función PHP muestra información sobre la configuración del servidor y la versión de PHP instalada?', ops:['php_info()','server_info()','phpinfo()','getconfig()'], r:2, e:'phpinfo() muestra una página con toda la información de configuración de PHP, extensiones cargadas, variables de entorno y directivas php.ini.' },
    { tema:'UF1', p:'¿Qué archivo de configuración principal usa PHP para establecer sus directivas?', ops:['php.conf','httpd.ini','php.ini','server.cfg'], r:2, e:'php.ini es el archivo de configuración principal de PHP donde se definen directivas como max_execution_time, upload_max_filesize, display_errors, etc.' },
    { tema:'UF1', p:'¿Qué significa el modelo cliente-servidor en aplicaciones web?', ops:['El cliente y el servidor ejecutan el mismo código','El servidor está a la espera de peticiones de clientes para servirles recursos','El cliente almacena todos los datos de la aplicación','El servidor solo gestiona bases de datos'], r:1, e:'En el modelo cliente-servidor el servidor permanece en escucha de peticiones de clientes. El cliente solicita recursos y el servidor los busca y sirve.' },
    { tema:'UF1', p:'¿En qué se diferencia el procesamiento en el servidor del procesamiento en el cliente?', ops:['No hay diferencia, ambos ejecutan el mismo código','El servidor ejecuta código (PHP, Java...) antes de enviar el HTML al cliente; el cliente ejecuta JavaScript en el navegador','El cliente es más potente que el servidor siempre','El servidor solo sirve archivos estáticos, nunca procesa'], r:1, e:'El servidor ejecuta lenguajes de servidor (PHP, Java, Python...) antes de enviar la respuesta HTML al cliente. El cliente ejecuta JavaScript en el navegador.' },
    { tema:'UF1', p:'¿Qué stack tecnológico es libre y usa Apache, MySQL y PHP?', ops:['WISA','MEAN','LAMP','MERN'], r:2, e:'LAMP = Linux + Apache + MySQL + PHP. Es el stack libre más clásico para desarrollo web en entorno servidor.' },
    { tema:'UF1', p:'¿Cuál es el stack equivalente propietario al LAMP?', ops:['WISA','MEAN','MAMP','LEMP'], r:0, e:'WISA = Windows + IIS + SQL Server + ASP. Es el equivalente propietario de Microsoft al stack LAMP libre.' },
    { tema:'UF1', p:'¿Qué extensión tienen los archivos de código PHP?', ops:['.html','.php','.asp','.jsp'], r:1, e:'Los archivos PHP tienen extensión .php. El servidor web los procesa antes de enviar el resultado HTML al navegador del cliente.' },
    { tema:'UF1', p:'¿Con qué etiquetas se delimita el código PHP dentro de un archivo?', ops:['&lt;php&gt; ... &lt;/php&gt;','&lt;? ... ?&gt;','&lt;?php ... ?&gt;','&lt;script type="php"&gt;...&lt;/script&gt;'], r:2, e:'El código PHP se delimita con <?php al inicio y ?> al final. Es la forma estándar y recomendada.' },
    { tema:'UF1', p:'¿Qué hace la directiva "display_errors" en php.ini?', ops:['Activa o desactiva la visualización de errores PHP en el navegador','Establece el tamaño máximo de los archivos subidos','Define el tiempo máximo de ejecución de un script','Configura la conexión a la base de datos'], r:0, e:'display_errors controla si los errores de PHP se muestran en el navegador. Debe estar Off en producción y On en desarrollo.' },
    { tema:'UF1', p:'¿Qué herramienta es MAMP?', ops:['Un framework PHP para desarrollo web','Un entorno de servidor local para macOS que incluye Apache, MySQL y PHP','Un sistema de control de versiones para PHP','Un gestor de dependencias para proyectos PHP'], r:1, e:'MAMP es un entorno de servidor local para macOS (también existe WAMP para Windows y XAMPP multiplataforma) que instala Apache, MySQL y PHP.' },
    { tema:'UF1', p:'¿Qué significa que PHP es un lenguaje "interpretado"?', ops:['El código PHP se compila a código máquina antes de ejecutarse','El código PHP se procesa línea a línea en tiempo de ejecución por el intérprete','El código PHP solo funciona en el navegador','El código PHP requiere instalación en el cliente'], r:1, e:'PHP es interpretado: el motor PHP lee y ejecuta el código línea a línea en tiempo de ejecución, sin una fase previa de compilación a código máquina.' },
    { tema:'UF1', p:'¿Cuál es la función del servidor web (Apache, Nginx) en la arquitectura de una aplicación PHP?', ops:['Ejecutar directamente el código PHP','Recibir peticiones HTTP del cliente y pasarlas al intérprete PHP, luego devolver la respuesta','Gestionar la base de datos de la aplicación','Compilar el código PHP a código máquina'], r:1, e:'El servidor web recibe la petición HTTP, detecta que es PHP, la pasa al intérprete PHP, recibe el HTML resultante y lo devuelve al cliente.' },
    { tema:'UF1', p:'¿Qué supervariable PHP contiene los datos enviados por un formulario con method="POST"?', ops:['$_GET','$_REQUEST','$_POST','$_FORM'], r:2, e:'$_POST contiene los datos enviados al servidor mediante el método POST de HTTP, típicamente desde formularios HTML.' },
    { tema:'UF1', p:'¿Qué supervariable PHP contiene los parámetros enviados en la URL?', ops:['$_URL','$_PARAM','$_GET','$_REQUEST'], r:2, e:'$_GET contiene los parámetros enviados en la URL (query string), por ejemplo: pagina.php?id=5 → $_GET["id"] = "5".' },
    { tema:'UF1', p:'¿Cuál es la diferencia principal entre GET y POST en formularios HTML?', ops:['GET es más seguro que POST siempre','GET adjunta datos en la URL (visible); POST los envía en el cuerpo de la petición (no visible en URL)','POST es más rápido que GET siempre','No hay diferencia práctica entre ambos métodos'], r:1, e:'GET adjunta los datos en la URL (visibles, limitados en tamaño). POST los envía en el cuerpo de la petición (no visibles en URL, sin límite práctico).' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF2 — PHP BÁSICO
  // ─────────────────────────────────────────────────────────
  UF2: [
    { tema:'UF2', p:'¿Cómo se delimita el código PHP embebido en un documento HTML?', ops:['Con las etiquetas &lt;php&gt; y &lt;/php&gt;','Con las etiquetas &lt;?php y ?&gt;','Con las etiquetas &lt;script&gt; y &lt;/script&gt;','Con comentarios HTML &lt;!-- php --&gt;'], r:1, e:'El código PHP se embebe en HTML usando <?php para abrir y ?> para cerrar. Esta combinación de código cliente (HTML) y servidor (PHP) se llama código embebido.' },
    { tema:'UF2', p:'¿Con qué símbolo empiezan los nombres de variables en PHP?', ops:['@','#','$','&'], r:2, e:'En PHP todas las variables empiezan con el símbolo $. Ejemplo: $nombre, $edad, $precio. No pueden empezar con número ni contener espacios.' },
    { tema:'UF2', p:'¿Qué instrucción PHP muestra datos por pantalla (en el HTML)?', ops:['print_screen()','display()','echo','show()'], r:2, e:'echo es la instrucción principal para mostrar datos en PHP. También existe print(), pero echo es más usado. Pueden mostrar variables, strings, HTML, expresiones.' },
    { tema:'UF2', p:'¿Cómo se concatenan cadenas en PHP?', ops:['Con el operador +','Con el operador &','Con el operador . (punto)','Con la función concat()'], r:2, e:'PHP usa el operador . (punto) para concatenar cadenas. Ejemplo: $saludo = "Hola " . $nombre; También existe .= para concatenar y asignar.' },
    { tema:'UF2', p:'¿Qué diferencia hay entre comillas dobles y simples en PHP al definir strings?', ops:['No hay ninguna diferencia','Las comillas dobles permiten interpolar variables y caracteres de escape; las simples las tratan como texto literal','Las simples son más rápidas siempre','Las dobles solo funcionan con caracteres ASCII'], r:1, e:'Con comillas dobles: "Hola $nombre" interpola la variable. Con comillas simples: \'Hola $nombre\' muestra literalmente "$nombre". Las dobles también procesan \n, \t, etc.' },
    { tema:'UF2', p:'¿Qué operador PHP comprueba igualdad en valor Y tipo de datos (estricto)?', ops:['==','!=','===','!=='], r:2, e:'=== (triple igual) comprueba que dos valores son iguales en valor Y en tipo. Ejemplo: 5 == "5" es true, pero 5 === "5" es false (uno es int, otro string).' },
    { tema:'UF2', p:'¿Qué hace el operador % en PHP?', ops:['División entera','Módulo: devuelve el resto de la división entera','Potencia','Raíz cuadrada'], r:1, e:'% es el operador módulo (resto de la división). Ejemplo: 10 % 3 = 1 porque 10 = 3*3 + 1. Útil para saber si un número es par (n % 2 == 0).' },
    { tema:'UF2', p:'¿Qué operador PHP se usa para la potencia (elevado a)?', ops:['^ ','pow','**','^*'], r:2, e:'El operador ** calcula la potencia en PHP. Ejemplo: $c = $a ** $b calcula a elevado a b. La función pow($a, $b) hace lo mismo.' },
    { tema:'UF2', p:'¿Qué es un array en PHP?', ops:['Una variable que almacena un único valor de cualquier tipo','Una estructura que puede almacenar múltiples valores bajo un mismo nombre, accesibles por índice o clave','Un tipo de función especial','Un tipo de objeto orientado a objetos'], r:1, e:'Un array almacena múltiples valores bajo un mismo nombre. Puede ser indexado (índices numéricos), asociativo (claves string) o multidimensional.' },
    { tema:'UF2', p:'¿Cómo se define un array en PHP (sintaxis moderna)?', ops:['array(1,2,3)','[1, 2, 3]','new Array(1,2,3)','list(1,2,3)'], r:1, e:'La sintaxis moderna usa corchetes: $arr = [1, 2, 3]; La clásica usa array(): $arr = array(1, 2, 3); Ambas son válidas, pero la de corchetes es más concisa.' },
    { tema:'UF2', p:'¿Qué es un array asociativo en PHP?', ops:['Un array con índices numéricos automáticos','Un array donde los elementos se acceden mediante claves string en lugar de índices numéricos','Un array que solo acepta valores de tipo string','Un array que no puede modificarse'], r:1, e:'Los arrays asociativos usan claves string: $persona = ["nombre" => "Ana", "edad" => 25]; Se accede con $persona["nombre"].' },
    { tema:'UF2', p:'¿Qué función PHP recorre todos los elementos de un array?', ops:['for','while','foreach','loop'], r:2, e:'foreach es la forma más cómoda de recorrer arrays en PHP: foreach($array as $valor) o foreach($array as $clave => $valor) para arrays asociativos.' },
    { tema:'UF2', p:'¿Qué función PHP devuelve el número de elementos de un array?', ops:['size()','length()','count()','sizeof() o count()'], r:3, e:'count($array) devuelve el número de elementos. sizeof() es un alias de count() y hace lo mismo. Ambas son válidas.' },
    { tema:'UF2', p:'¿Qué función PHP añade un elemento al final de un array?', ops:['array_add()','push()','array_push() o $arr[]= valor','append()'], r:2, e:'array_push($arr, $valor) añade al final. La forma más corta es $arr[] = $valor, que automáticamente añade al final con el siguiente índice numérico.' },
    { tema:'UF2', p:'¿Qué función PHP ordena un array de menor a mayor?', ops:['order()','asort()','sort()','array_sort()'], r:2, e:'sort($array) ordena el array de menor a mayor reindexando. asort() mantiene las asociaciones clave-valor. rsort() ordena de mayor a menor.' },
    { tema:'UF2', p:'¿Qué función PHP devuelve la longitud de una cadena?', ops:['length()','size()','strlen()','strcount()'], r:2, e:'strlen($cadena) devuelve el número de bytes (caracteres) de la cadena. Para cadenas multibyte (UTF-8 con acentos) se debe usar mb_strlen().' },
    { tema:'UF2', p:'¿Qué función PHP convierte una cadena a minúsculas?', ops:['lowercase()','str_lower()','strtolower()','toLower()'], r:2, e:'strtolower($cadena) convierte todos los caracteres a minúsculas. strtoupper() los convierte a mayúsculas.' },
    { tema:'UF2', p:'¿Qué función PHP busca la posición de una subcadena dentro de otra?', ops:['str_find()','search()','strpos()','find()'], r:2, e:'strpos($cadena, $buscar) devuelve la posición (0-based) de la primera ocurrencia. Devuelve false si no la encuentra. strrpos() encuentra la última ocurrencia.' },
    { tema:'UF2', p:'¿Qué función PHP reemplaza todas las ocurrencias de una subcadena en otra?', ops:['str_swap()','replace()','str_replace()','strreplace()'], r:2, e:'str_replace($buscar, $reemplazar, $cadena) reemplaza todas las ocurrencias de $buscar por $reemplazar en $cadena.' },
    { tema:'UF2', p:'¿Qué función PHP devuelve la fecha y hora actual del servidor?', ops:['getdate()','now()','date()','time_now()'], r:2, e:'date($formato) devuelve la fecha actual del servidor formateada. Ejemplo: date("d/m/Y") devuelve "15/03/2025". date("H:i:s") devuelve la hora.' },
    { tema:'UF2', p:'¿Qué hace la función trim() en PHP?', ops:['Recorta una cadena a un número máximo de caracteres','Elimina espacios en blanco (u otros caracteres) al inicio y al final de una cadena','Divide una cadena en un array','Convierte la cadena a mayúsculas'], r:1, e:'trim($cadena) elimina espacios en blanco al inicio y al final. ltrim() solo por la izquierda, rtrim() solo por la derecha.' },
    { tema:'UF2', p:'¿Qué hace $a++ en PHP?', ops:['Incrementa $a en 2','Decrementa $a en 1','Incrementa $a en 1 (post-incremento)','Multiplica $a por sí mismo'], r:2, e:'$a++ es el operador de post-incremento: devuelve el valor actual de $a y luego lo incrementa en 1. ++$a es el pre-incremento: incrementa primero y luego devuelve el valor.' },
    { tema:'UF2', p:'¿Cuál es la diferencia entre include_once y include en PHP?', ops:['No hay diferencia','include_once verifica si el archivo ya fue incluido antes y no lo incluye de nuevo si ya lo fue; include lo incluye siempre','include_once es más rápido','include_once genera error si el archivo no existe'], r:1, e:'include_once y require_once verifican si el archivo ya fue incluido en el script actual y lo omiten si es así, evitando declaraciones duplicadas de funciones o clases.' },
    { tema:'UF2', p:'¿PHP es un lenguaje case-sensitive (distingue mayúsculas y minúsculas)?', ops:['No, nunca distingue mayúsculas de minúsculas','Sí, siempre distingue en todo','Sí para nombres de variables ($var y $Var son distintas); No para nombres de funciones y clases','No para variables, Sí para funciones'], r:2, e:'PHP es case-sensitive para variables: $nombre y $Nombre son variables distintas. No lo es para funciones y clases: strlen() y STRLEN() son la misma función.' },
    { tema:'UF2', p:'¿Qué es una constante en PHP y cómo se define?', ops:['Una variable que no puede cambiar; se define con $CONST nombre = valor','Un valor fijo que no puede cambiar durante la ejecución; se define con define("NOMBRE", valor) o const NOMBRE = valor','Una variable global del sistema','Una variable que se comparte entre todos los scripts'], r:1, e:'Una constante tiene un valor fijo que no cambia. Se define con define("PI", 3.14159) o const PI = 3.14159. Por convención se usan MAYÚSCULAS. No llevan $ como las variables.' },
    { tema:'UF2', p:'¿Qué hace la estructura switch en PHP?', ops:['Itera sobre un array','Compara una variable con múltiples valores posibles y ejecuta el bloque correspondiente al que coincida','Define una función con múltiples casos de uso','Gestiona excepciones de forma múltiple'], r:1, e:'switch($variable) { case valor1: ... break; case valor2: ... break; default: ... } evalúa la variable y ejecuta el bloque del case que coincida.' },
    { tema:'UF2', p:'¿Qué hace la instrucción break dentro de un switch de PHP?', ops:['Sale del bucle más externo','Salta al siguiente case','Sale del switch (o del bucle) evitando que continúe con los siguientes cases','Reinicia la ejecución del switch'], r:2, e:'break dentro de switch detiene la ejecución del switch y sale de él. Sin break, PHP continúa ejecutando los cases siguientes (fall-through), lo que raramente es lo que se quiere.' },
    { tema:'UF2', p:'¿Cómo se define una función en PHP?', ops:['def nombreFuncion($param) { }','func nombreFuncion($param) { }','function nombreFuncion($param) { }','method nombreFuncion($param) { }'], r:2, e:'function nombreFuncion($parametro) { // código; return $resultado; } define una función reutilizable en PHP.' },
    { tema:'UF2', p:'¿Qué hace la sentencia return en una función PHP?', ops:['Sale del script completamente','Imprime un valor en pantalla','Devuelve un valor al código que llamó la función y termina su ejecución','Guarda el valor en una variable global'], r:2, e:'return $valor; devuelve un valor desde la función al punto donde fue llamada y termina la ejecución de la función. Sin return, la función devuelve null.' },
    { tema:'UF2', p:'¿Qué son las constantes mágicas en PHP?', ops:['Constantes que el programador define en mayúsculas','Constantes predefinidas por PHP que cambian según el contexto (archivo, línea, función, clase...) como __LINE__, __FILE__, __CLASS__','Variables globales que no pueden eliminarse','Constantes importadas de otros lenguajes'], r:1, e:'Las constantes mágicas (__LINE__, __FILE__, __DIR__, __FUNCTION__, __CLASS__, etc.) cambian de valor según el contexto donde se usen. Se rodean de doble guion bajo.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF3 — PHP AVANZADO
  // ─────────────────────────────────────────────────────────
  UF3: [
    { tema:'UF3', p:'¿Qué es un ataque XSS (Cross-Site Scripting)?', ops:['Un ataque de fuerza bruta a la base de datos','Un ataque en el que se inyecta código malicioso (normalmente JavaScript) en una página web para que lo ejecuten otros usuarios','Un ataque de denegación de servicio al servidor web','Un ataque que intercepta las comunicaciones entre cliente y servidor'], r:1, e:'XSS permite a un atacante inyectar código (usualmente JavaScript) en una página web. Cuando otros usuarios la visitan, el navegador ejecuta ese código malicioso.' },
    { tema:'UF3', p:'¿Qué función PHP convierte caracteres especiales HTML (<, >, &, ") en entidades HTML para prevenir XSS?', ops:['strip_tags()','html_encode()','htmlspecialchars()','sanitize()'], r:2, e:'htmlspecialchars() convierte caracteres como <, >, &, " en sus equivalentes entidades HTML (&lt;, &gt;, etc.), evitando que se ejecuten como código.' },
    { tema:'UF3', p:'¿Qué hace la función strip_tags() en PHP?', ops:['Elimina espacios en blanco de una cadena','Elimina todas las etiquetas HTML y PHP de una cadena','Convierte las etiquetas HTML en entidades','Valida que una cadena no contenga SQL'], r:1, e:'strip_tags() elimina todas las etiquetas HTML y PHP de una cadena, dejando solo el texto plano. Útil para sanear entradas de usuario.' },
    { tema:'UF3', p:'¿Cuál es la diferencia entre XSS directo e indirecto?', ops:['El directo afecta al servidor; el indirecto al cliente','En el directo el código malicioso se inyecta en un formulario; en el indirecto se modifica el valor de una variable (por ejemplo en la URL)','No hay diferencia, son el mismo tipo de ataque','El directo usa POST; el indirecto usa GET'], r:1, e:'XSS directo: el código malicioso se introduce directamente en un input. XSS indirecto: se suplanta el valor de una variable (ej: parámetro GET en la URL).' },
    { tema:'UF3', p:'¿Qué función PHP sirve para validar una cadena contra un patrón de expresión regular?', ops:['strpos()','preg_match()','in_array()','filter_var()'], r:1, e:'preg_match() compara una cadena contra un patrón de expresión regular y devuelve 1 si coincide, 0 si no, o false en caso de error.' },
    { tema:'UF3', p:'¿Qué supone usar campos de tipo "hidden" en formularios PHP?', ops:['Son campos completamente seguros e invisibles para el usuario','Permiten pasar información entre páginas, pero el usuario puede verlos e incluso modificarlos si accede al código fuente','Cifran automáticamente la información que contienen','No pueden ser manipulados por el usuario bajo ninguna circunstancia'], r:1, e:'Los campos hidden pasan información entre páginas de forma invisible en el formulario, pero el usuario puede verlos e incluso modificarlos usando las herramientas del navegador.' },
    { tema:'UF3', p:'¿Qué función PHP comprueba si una variable está definida y no es null?', ops:['defined()','is_set()','isset()','exists()'], r:2, e:'isset() devuelve true si la variable está definida y su valor no es null. Es imprescindible antes de usar $_GET, $_POST o $_SESSION.' },
    { tema:'UF3', p:'¿Qué es una sesión PHP?', ops:['Una conexión permanente a la base de datos','Un mecanismo para almacenar información del usuario en el servidor entre diferentes peticiones HTTP','Un tipo de cookie cifrada almacenada en el navegador','Una conexión WebSocket entre cliente y servidor'], r:1, e:'Una sesión PHP almacena datos del usuario en el servidor (en archivos o memoria) asociados a un identificador de sesión único, permitiendo persistir información entre peticiones.' },
    { tema:'UF3', p:'¿Qué función PHP inicia o reanuda una sesión?', ops:['session_create()','init_session()','session_start()','start_session()'], r:2, e:'session_start() inicia una nueva sesión o reanuda la existente. Debe llamarse al principio del script, antes de cualquier salida HTML.' },
    { tema:'UF3', p:'¿Dónde se almacenan los datos de sesión en PHP por defecto?', ops:['En una cookie en el navegador del cliente','En la base de datos de la aplicación','En archivos temporales en el servidor','En la memoria RAM del cliente'], r:2, e:'Por defecto, PHP almacena los datos de sesión en archivos temporales en el servidor (directorio configurado en session.save_path en php.ini).' },
    { tema:'UF3', p:'¿Qué supervariable PHP contiene los datos de sesión?', ops:['$_COOKIE','$_SESSION','$_SERVER','$_ENV'], r:1, e:'$_SESSION es un array superglobal que almacena los datos de sesión del usuario, accesibles en cualquier página que haya ejecutado session_start().' },
    { tema:'UF3', p:'¿Qué función PHP destruye todos los datos de la sesión actual?', ops:['session_stop()','session_close()','session_destroy()','unset_session()'], r:2, e:'session_destroy() destruye todos los datos asociados a la sesión actual en el servidor. Para un logout completo también hay que eliminar la cookie y hacer unset($_SESSION).' },
    { tema:'UF3', p:'¿Qué es una cookie en PHP?', ops:['Una variable almacenada en el servidor','Un pequeño archivo de texto que el servidor envía al navegador del cliente para almacenar información','Un tipo de sesión cifrada en el servidor','Una variable de entorno del servidor web'], r:1, e:'Una cookie es un pequeño fragmento de datos que el servidor envía al navegador mediante la cabecera Set-Cookie. El navegador lo almacena y lo reenvía en peticiones futuras.' },
    { tema:'UF3', p:'¿Qué función PHP establece una cookie?', ops:['create_cookie()','set_cookie()','setcookie()','cookie_set()'], r:2, e:'setcookie() establece una cookie que se enviará al cliente con la respuesta HTTP. Debe llamarse antes de cualquier salida HTML.' },
    { tema:'UF3', p:'¿Cuál es la diferencia principal entre cookies y sesiones?', ops:['Las cookies son más seguras que las sesiones','Las cookies almacenan datos en el cliente (navegador); las sesiones almacenan datos en el servidor','Las sesiones duran más que las cookies siempre','No hay diferencia práctica entre ambas'], r:1, e:'Las cookies guardan datos en el navegador del cliente (visibles y modificables). Las sesiones guardan datos en el servidor (más seguras), usando solo un ID en el cliente.' },
    { tema:'UF3', p:'¿Qué función PHP redirige al navegador a otra URL?', ops:['redirect()','go_to()','header("Location: url")','navigate()'], r:2, e:'header("Location: url") envía una cabecera HTTP de redirección al navegador. Debe llamarse antes de cualquier salida HTML y suele ir seguida de exit().' },
    { tema:'UF3', p:'¿Qué hace la función header() en PHP?', ops:['Genera el encabezado HTML de una página','Envía cabeceras HTTP al navegador (Content-Type, Location, Set-Cookie, etc.)','Lee las cabeceras de la petición del cliente','Establece el título de la página web'], r:1, e:'header() envía cabeceras HTTP directas al navegador. Se usa para redirecciones, establecer el tipo de contenido, descargar archivos o configurar caché.' },
    { tema:'UF3', p:'¿Qué atributo de cookie impide que JavaScript acceda a ella, mitigando XSS?', ops:['Secure','SameSite','HttpOnly','Private'], r:2, e:'El atributo HttpOnly impide el acceso a la cookie desde JavaScript (document.cookie). Solo el servidor puede leerla, lo que mitiga el robo de cookies mediante XSS.' },
    { tema:'UF3', p:'¿Para qué sirve el atributo "Secure" en una cookie?', ops:['Para que la cookie solo se transmita sobre conexiones HTTPS','Para que JavaScript no pueda acceder a la cookie','Para que la cookie no expire nunca','Para cifrar el contenido de la cookie'], r:0, e:'El atributo Secure indica que la cookie solo debe enviarse en conexiones HTTPS cifradas, protegiéndola de interceptación en conexiones HTTP.' },
    { tema:'UF3', p:'¿Qué es la inyección SQL y cómo se previene en PHP?', ops:['Es un error de sintaxis en PHP; se previene revisando el código','Es un ataque donde se inserta SQL malicioso en una entrada; se previene con consultas preparadas (prepared statements)','Es un fallo del servidor MySQL; se previene actualizando MySQL','Es un ataque de red; se previene con firewall'], r:1, e:'La inyección SQL inserta código SQL malicioso en entradas de usuario para manipular la base de datos. Se previene con prepared statements (PDO o MySQLi) que separan código y datos.' },
    { tema:'UF3', p:'¿Qué función PHP lanza para incluir y ejecutar el contenido de otro archivo PHP?', ops:['import()','execute()','include() o require()','load()'], r:2, e:'include() y require() insertan y ejecutan el contenido de otro archivo PHP. La diferencia: include genera un warning si no existe; require genera un error fatal.' },
    { tema:'UF3', p:'¿Cuál es la diferencia entre include() y require() en PHP?', ops:['include() solo incluye HTML; require() incluye PHP','Con include(), si el archivo no existe se genera un warning y el script continúa; con require(), genera un error fatal y el script se detiene','require() es más rápido que include()','No hay diferencia entre ambas funciones'], r:1, e:'Si el archivo no existe: include() genera E_WARNING y el script continúa ejecutándose. require() genera E_COMPILE_ERROR y el script se detiene completamente.' },
    { tema:'UF3', p:'¿Qué es la programación orientada a objetos (POO) en PHP?', ops:['Un paradigma donde el código se organiza en funciones independientes','Un paradigma donde el código se organiza en clases que encapsulan datos (atributos) y comportamiento (métodos)','Un paradigma exclusivo de Java','Un sistema de templates para PHP'], r:1, e:'La POO organiza el código en clases que definen atributos (datos) y métodos (comportamiento). En PHP se define con class, se instancian objetos con new.' },
    { tema:'UF3', p:'¿Qué palabra clave PHP se usa para crear una instancia de una clase?', ops:['create','instance','new','make'], r:2, e:'La palabra clave new crea una nueva instancia de una clase (objeto). Ejemplo: $obj = new MiClase();' },
    { tema:'UF3', p:'¿Qué es el método __construct() en una clase PHP?', ops:['Un método que se llama cuando el objeto es destruido','Un método especial que se ejecuta automáticamente al crear una instancia de la clase (constructor)','Un método para convertir el objeto a string','Un método para clonar el objeto'], r:1, e:'__construct() es el constructor de la clase. Se ejecuta automáticamente cuando se crea un nuevo objeto con new. Se usa para inicializar propiedades.' },
    { tema:'UF3', p:'¿Cómo se accede a las propiedades y métodos de un objeto en PHP?', ops:['Con el operador "::" para todos los casos','Con el operador "->" para instancias y "::" para métodos/propiedades estáticas','Con el operador "." como en JavaScript','Con el operador "@" para propiedades privadas'], r:1, e:'El operador -> accede a propiedades y métodos de una instancia de objeto. El operador :: (Paamayim Nekudotayim) accede a propiedades y métodos estáticos.' },
    { tema:'UF3', p:'¿Qué es la herencia en PHP y cómo se implementa?', ops:['La herencia permite que una clase reutilice código de otra clase padre; se implementa con la palabra clave "extends"','La herencia es cuando una función llama a otra función','Se implementa con la palabra clave "inherits"','La herencia no existe en PHP'], r:0, e:'La herencia permite que una clase hija reutilice propiedades y métodos de una clase padre. En PHP: class Hija extends Padre { }' },
    { tema:'UF3', p:'¿Para qué sirven los namespaces (espacios de nombres) en PHP?', ops:['Para gestionar la memoria del servidor','Para organizar el código y evitar conflictos de nombres entre clases de diferentes librerías','Para definir el espacio de almacenamiento de variables','Para separar el código PHP del HTML'], r:1, e:'Los namespaces organizan el código en espacios lógicos y evitan conflictos de nombres cuando dos librerías tienen clases con el mismo nombre. Se declaran con namespace.' },
    { tema:'UF3', p:'¿Qué hace la función password_hash() en PHP?', ops:['Cifra una contraseña con MD5','Genera un hash seguro de una contraseña usando bcrypt u otros algoritmos seguros','Compara dos contraseñas','Genera una contraseña aleatoria'], r:1, e:'password_hash() genera un hash seguro de una contraseña usando bcrypt (u otros algoritmos) con sal (salt) automática. Nunca se deben guardar contraseñas en texto plano.' },
    { tema:'UF3', p:'¿Qué función PHP verifica si una contraseña coincide con su hash generado por password_hash()?', ops:['password_check()','hash_verify()','password_verify()','check_password()'], r:2, e:'password_verify($password, $hash) compara una contraseña en texto plano con su hash previamente generado por password_hash(). Devuelve true o false.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF4 — ACCESO A DATOS CON PHP
  // ─────────────────────────────────────────────────────────
  UF4: [
    { tema:'UF4', p:'¿Qué es PDO en PHP?', ops:['Un servidor de bases de datos para PHP','PHP Data Objects: una extensión PHP que proporciona una interfaz uniforme para acceder a distintas bases de datos','Un ORM completo para PHP','Un sistema de caché de consultas SQL'], r:1, e:'PDO (PHP Data Objects) es una extensión PHP que ofrece una interfaz consistente para acceder a múltiples tipos de bases de datos (MySQL, PostgreSQL, SQLite, etc.).' },
    { tema:'UF4', p:'¿Qué ventaja principal ofrece PDO frente a usar las funciones mysql_* directamente?', ops:['PDO es más rápido en todos los casos','PDO ofrece una interfaz unificada para múltiples SGBD y soporta nativamente prepared statements','PDO gestiona automáticamente los errores','PDO es la única forma de conectar PHP a MySQL'], r:1, e:'PDO permite cambiar de SGBD modificando mínimamente el código, y soporta prepared statements de forma nativa, previniendo inyecciones SQL.' },
    { tema:'UF4', p:'¿Qué método PDO se usa para operaciones INSERT, UPDATE y DELETE?', ops:['$pdo->query($sql)','$pdo->prepare($sql)','$pdo->exec($sql)','$pdo->run($sql)'], r:2, e:'$pdo->exec($sql) ejecuta una instrucción SQL que no retorna filas (INSERT, UPDATE, DELETE) y devuelve el número de filas afectadas.' },
    { tema:'UF4', p:'¿Qué método PDO se usa para operaciones SELECT que retornan datos?', ops:['$pdo->exec($sql)','$pdo->select($sql)','$pdo->query($sql)','$pdo->fetch($sql)'], r:2, e:'$pdo->query($sql) ejecuta una consulta SELECT y devuelve un objeto PDOStatement con los resultados, que se pueden recorrer con fetch().' },
    { tema:'UF4', p:'¿Qué son las declaraciones preparadas (prepared statements) en PDO?', ops:['Consultas SQL guardadas como archivos de texto','Consultas SQL donde los parámetros se definen con marcadores y se vinculan después, separando código SQL de datos para prevenir inyección SQL','Una forma de hacer consultas más rápidas','Procedimientos almacenados en la base de datos'], r:1, e:'Las declaraciones preparadas separan la estructura SQL de los datos de usuario, enviándolos por separado al servidor de BD. Previenen inyección SQL de forma efectiva.' },
    { tema:'UF4', p:'¿Qué método PDOStatement recupera la siguiente fila de un resultado SELECT?', ops:['$stmt->get()','$stmt->next()','$stmt->fetch()','$stmt->row()'], r:2, e:'fetch() recupera la siguiente fila del conjunto de resultados como un array. Devuelve null cuando no hay más filas, por lo que se usa en bucles while.' },
    { tema:'UF4', p:'¿Cómo se establece el modo de error en PDO para que lance excepciones?', ops:['$pdo->setError(PDO::THROW_EXCEPTION)','$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION)','$pdo->enableExceptions(true)','$pdo->setMode("exception")'], r:1, e:'$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION) hace que PDO lance PDOException en caso de error, que podemos capturar con try-catch.' },
    { tema:'UF4', p:'¿Qué clase de excepción lanza PDO cuando ocurre un error de base de datos?', ops:['DBException','SQLException','PDOException','DatabaseException'], r:2, e:'PDO lanza PDOException cuando ocurre un error de base de datos (si se configura el modo ERRMODE_EXCEPTION). Hereda de RuntimeException.' },
    { tema:'UF4', p:'¿Qué es un DSN (Data Source Name) en PDO?', ops:['El nombre del usuario de la base de datos','La cadena que especifica el driver, host y nombre de base de datos para la conexión PDO','El nombre del servidor de base de datos','La contraseña de acceso a la base de datos'], r:1, e:'El DSN (Data Source Name) es la cadena que describe cómo conectar a la base de datos: driver, host, puerto y nombre. Ejemplo: "mysql:host=localhost;dbname=mibd".' },
    { tema:'UF4', p:'¿Qué formato usa PHP para trabajar con datos XML?', ops:['Solo se puede usar con la función xml_parse()','PHP ofrece SimpleXML, XMLReader, XMLWriter y DOMDocument para trabajar con XML','PHP no soporta XML nativamente','Solo se puede trabajar con XML usando XSLT'], r:1, e:'PHP ofrece varias opciones para XML: SimpleXML (más sencilla), XMLReader/XMLWriter (streaming para archivos grandes) y DOMDocument (más completa).' },
    { tema:'UF4', p:'¿Qué función carga un archivo XML en un objeto SimpleXMLElement?', ops:['xml_load_file()','simplexml_open()','simplexml_load_file()','load_xml()'], r:2, e:'simplexml_load_file($ruta) carga un archivo XML y lo convierte en un objeto SimpleXMLElement que se puede recorrer con foreach.' },
    { tema:'UF4', p:'¿Qué es JSON y para qué se usa en aplicaciones web?', ops:['Un sistema de base de datos NoSQL','JavaScript Object Notation: un formato de texto ligero para intercambio de datos entre cliente y servidor','Un framework JavaScript para consumir APIs','Un tipo especial de HTML para datos dinámicos'], r:1, e:'JSON (JavaScript Object Notation) es un formato de texto ligero basado en pares clave-valor para intercambio de datos. Ha sustituido prácticamente a XML en APIs REST.' },
    { tema:'UF4', p:'¿Qué función PHP convierte un array u objeto PHP a una cadena JSON?', ops:['json_serialize()','array_to_json()','json_encode()','to_json()'], r:2, e:'json_encode($dato) convierte un array u objeto PHP a su representación JSON como cadena de texto. Devuelve false en caso de error.' },
    { tema:'UF4', p:'¿Qué función PHP convierte una cadena JSON a un array u objeto PHP?', ops:['json_deserialize()','json_to_array()','json_parse()','json_decode()'], r:3, e:'json_decode($json) convierte una cadena JSON a un objeto PHP (o array si se pasa true como segundo parámetro). Devuelve null en caso de error.' },
    { tema:'UF4', p:'¿Cuál es la diferencia entre json_decode($json) y json_decode($json, true)?', ops:['No hay diferencia entre ambas llamadas','json_decode($json) retorna un objeto PHP; json_decode($json, true) retorna un array asociativo','json_decode($json, true) es más lento','json_decode($json, true) solo funciona con arrays JSON, no con objetos'], r:1, e:'Sin el segundo parámetro, json_decode devuelve un objeto stdClass. Con true devuelve un array asociativo, más fácil de manejar en PHP.' },
    { tema:'UF4', p:'¿Cómo se leen y escriben archivos de texto en PHP?', ops:['Solo con la función file()','Con funciones como fopen(), fread(), fwrite(), fclose() o de forma simplificada con file_get_contents() y file_put_contents()','Solo mediante bases de datos','Con la función readfile() exclusivamente'], r:1, e:'PHP ofrece file_get_contents() (leer todo el archivo a string), file_put_contents() (escribir), y las funciones de bajo nivel fopen/fread/fwrite/fclose.' },
    { tema:'UF4', p:'¿Qué función PHP lee todo el contenido de un archivo en una cadena de texto?', ops:['read_file()','fget_contents()','file_get_contents()','file_read()'], r:2, e:'file_get_contents($ruta) lee todo el contenido de un archivo (o URL) y lo devuelve como cadena. Es la forma más sencilla de leer archivos en PHP.' },
    { tema:'UF4', p:'¿Por qué es importante crear un usuario de base de datos con permisos mínimos para la aplicación web?', ops:['Para que la aplicación funcione más rápido','Para limitar el daño potencial en caso de inyección SQL: si el atacante solo tiene permisos de SELECT, no puede borrar tablas','Para cumplir con la legislación GDPR','No es necesario, el usuario root es el más cómodo'], r:1, e:'El principio de mínimo privilegio: la aplicación solo debe tener los permisos que necesita. Si hay inyección SQL, el atacante solo puede hacer lo que permite ese usuario limitado.' },
    { tema:'UF4', p:'¿Qué significa CRUD en el contexto de bases de datos?', ops:['Create, Read, Update, Delete — las cuatro operaciones básicas sobre datos','Copy, Replace, Undo, Delete','Compile, Run, Update, Deploy','Create, Register, Use, Delete'], r:0, e:'CRUD = Create (INSERT), Read (SELECT), Update (UPDATE), Delete (DELETE). Son las cuatro operaciones básicas que cualquier aplicación realiza sobre una base de datos.' },
    { tema:'UF4', p:'¿Qué método PDOStatement vincula un valor a un marcador en una consulta preparada?', ops:['$stmt->addValue()','$stmt->bindValue() o $stmt->bindParam()','$stmt->setParam()','$stmt->link()'], r:1, e:'bindValue() vincula un valor directamente al marcador. bindParam() vincula una variable (por referencia). Ambos previenen inyección SQL al separar datos de la instrucción SQL.' },
    { tema:'UF4', p:'¿Cómo se indica un parámetro en una consulta preparada PDO con marcadores con nombre?', ops:['Con el símbolo # seguido del nombre (#id)','Con el símbolo ? para todos los parámetros','Con : seguido del nombre (:id, :nombre)','Con @ seguido del nombre (@id)'], r:2, e:'PDO permite marcadores con nombre usando : seguido del nombre (ej: :id, :nombre) o marcadores posicionales con ?. Los nombrados son más legibles.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF5 — FRAMEWORKS PARA PHP I (Laravel)
  // ─────────────────────────────────────────────────────────
  UF5: [
    { tema:'UF5', p:'¿Qué es Laravel?', ops:['Un servidor web alternativo a Apache','Un framework PHP de código abierto que sigue el patrón MVC para desarrollar aplicaciones web','Un sistema gestor de bases de datos para PHP','Un lenguaje de programación basado en PHP'], r:1, e:'Laravel es el framework PHP más popular, de código abierto, que sigue el patrón MVC. Ofrece herramientas para rutas, vistas (Blade), ORM (Eloquent), autenticación y más.' },
    { tema:'UF5', p:'¿Qué patrón de arquitectura sigue Laravel?', ops:['MVP (Model-View-Presenter)','MVVM (Model-View-ViewModel)','MVC (Model-View-Controller)','SOA (Service-Oriented Architecture)'], r:2, e:'Laravel sigue el patrón MVC: Model (lógica de datos/Eloquent), View (presentación/Blade templates), Controller (lógica de negocio/HTTP).' },
    { tema:'UF5', p:'¿Qué herramienta de línea de comandos usa Laravel para tareas de generación y mantenimiento?', ops:['composer','npm','php artisan','laravel-cli'], r:2, e:'php artisan es la herramienta CLI de Laravel. Permite crear controladores, modelos, migraciones, ejecutar tests, gestionar rutas, limpiar caché y mucho más.' },
    { tema:'UF5', p:'¿Qué gestor de dependencias se usa para instalar Laravel y sus paquetes?', ops:['npm','pip','Composer','Maven'], r:2, e:'Composer es el gestor de dependencias de PHP. Se usa para instalar Laravel y sus paquetes (definidos en composer.json).' },
    { tema:'UF5', p:'¿Dónde se definen las rutas web de una aplicación Laravel?', ops:['En el archivo app/Http/routes.php','En el directorio app/Controllers/','En el archivo routes/web.php','En el archivo config/routes.php'], r:2, e:'Las rutas web de Laravel se definen en routes/web.php. Las rutas de API van en routes/api.php. Cada ruta asocia una URL con un controlador o closure.' },
    { tema:'UF5', p:'¿Qué motor de plantillas usa Laravel para las vistas?', ops:['Twig','Smarty','Blade','Mustache'], r:2, e:'Blade es el motor de plantillas de Laravel. Los archivos de vista tienen extensión .blade.php y permiten usar directivas como @if, @foreach, @extends, @section.' },
    { tema:'UF5', p:'¿Qué directiva Blade se usa para mostrar el valor de una variable escapando HTML?', ops:['{!! $variable !!}','<? echo $variable ?>','{{ $variable }}','@echo($variable)'], r:2, e:'{{ $variable }} muestra el valor de la variable escapando el HTML (usa htmlspecialchars), previniendo XSS. Para HTML sin escapar se usa {!! $variable !!}.' },
    { tema:'UF5', p:'¿Qué diferencia hay entre {{ $var }} y {!! $var !!} en Blade?', ops:['No hay diferencia','{{ $var }} escapa el HTML (seguro contra XSS); {!! $var !!} muestra el HTML sin escapar (usar solo con datos de confianza)','{!! $var !!} es más rápido que {{ $var }}','{{ $var }} solo funciona con strings'], r:1, e:'{{ $var }} escapa caracteres HTML (previene XSS). {!! $var !!} muestra el HTML tal cual, sin escapar. Solo usar {!! !!} con contenido de confianza (nunca con datos del usuario).' },
    { tema:'UF5', p:'¿Qué directiva Blade permite que una vista hija extienda una vista padre (layout)?', ops:['@include','@parent','@extends','@layout'], r:2, e:'@extends("nombre.layout") indica que la vista hereda de un layout. La vista hija define secciones con @section que se insertan en los @yield del layout.' },
    { tema:'UF5', p:'¿Qué comando php artisan genera un nuevo controlador en Laravel?', ops:['php artisan new:controller NombreController','php artisan generate controller NombreController','php artisan make:controller NombreController','php artisan create:controller NombreController'], r:2, e:'php artisan make:controller NombreController crea un nuevo controlador en app/Http/Controllers/. Con --resource añade los métodos CRUD estándar.' },
    { tema:'UF5', p:'¿Qué hace el método validate() del objeto Request en Laravel?', ops:['Valida que el usuario esté autenticado','Valida los datos de la petición según reglas definidas; si falla, redirige automáticamente con los errores','Sanitiza automáticamente todos los campos del formulario','Verifica la firma digital de la petición'], r:1, e:'request()->validate([reglas]) valida los datos entrantes. Si falla, lanza ValidationException y Laravel redirige automáticamente al formulario con errores en $errors.' },
    { tema:'UF5', p:'¿Qué directiva Blade protege un formulario contra ataques CSRF?', ops:['@secure','@protect','@csrf','@token'], r:2, e:'@csrf inserta un campo oculto con un token CSRF en el formulario. Laravel verifica este token en cada petición POST, protegiendo contra ataques de falsificación de petición.' },
    { tema:'UF5', p:'¿Qué es CSRF (Cross-Site Request Forgery)?', ops:['Un ataque XSS que inyecta JavaScript','Un ataque que engaña al navegador del usuario para que realice peticiones no deseadas a un sitio en el que está autenticado','Un tipo de inyección SQL','Un ataque de denegación de servicio'], r:1, e:'CSRF engaña al usuario autenticado para que su navegador envíe peticiones maliciosas a la aplicación. Laravel lo previene con tokens CSRF únicos por sesión.' },
    { tema:'UF5', p:'¿Qué helper de Laravel genera la URL de una ruta nombrada?', ops:['url("nombre.ruta")','path("nombre.ruta")','route("nombre.ruta")','link("nombre.ruta")'], r:2, e:'route("nombre.ruta") genera la URL completa de una ruta nombrada. Las rutas se nombran con ->name("nombre") en routes/web.php.' },
    { tema:'UF5', p:'¿Qué clase gestiona las peticiones HTTP entrantes en Laravel?', ops:['HttpRequest','ServerRequest','Illuminate\\Http\\Request','LaravelRequest'], r:2, e:'Illuminate\\Http\\Request encapsula la petición HTTP entrante. Se inyecta en los métodos del controlador y permite acceder a los parámetros con $request->get() o $request->input().' },
    { tema:'UF5', p:'¿Cómo se define una ruta GET en Laravel que llama a un método de controlador?', ops:["Route::get('/ruta', 'Controlador@metodo')",'Route::get("/ruta", [Controlador::class, "metodo"])', 'Route::get("/ruta", function() { })', 'Cualquiera de las anteriores es válida en versiones actuales'], r:3, e:'Laravel acepta varias sintaxis. La moderna (Laravel 8+) es [Controlador::class, "metodo"]. La clásica "Controlador@metodo" también funciona. Los closures también son válidos.' },
    { tema:'UF5', p:'¿Qué método del Request de Laravel obtiene el valor de un campo del formulario?', ops:['$request->field("campo")','$request->get("campo") o $request->input("campo")','$request->param("campo")','$_POST["campo"]'], r:1, e:'$request->get("campo") o $request->input("campo") recuperan el valor de un campo de formulario de la petición HTTP (GET o POST).' },
    { tema:'UF5', p:'¿Qué son los Form Requests en Laravel?', ops:['Clases que representan formularios HTML','Clases especiales que encapsulan la lógica de validación y autorización de una petición HTTP, separándola del controlador','Middlewares para validar formularios','Vistas Blade para renderizar formularios'], r:1, e:'Los Form Requests son clases (php artisan make:request) que contienen los métodos rules() (reglas de validación), authorize() y messages() (mensajes personalizados).' },
    { tema:'UF5', p:'¿Dónde se almacenan los Form Requests en Laravel por defecto?', ops:['app/Http/Forms/','app/Requests/','app/Http/Requests/','app/Validators/'], r:2, e:'Los Form Requests se almacenan en app/Http/Requests/ por defecto. Se crean con: php artisan make:request NombreRequest.' },
    { tema:'UF5', p:'¿Qué directiva Blade muestra errores de validación en la vista?', ops:['$errors->get("campo")','@error("campo") ... @enderror','@if($errors->has("campo")) ... @endif','Cualquiera de las anteriores es válida'], r:3, e:'Todas son válidas. @error es la más limpia y nueva. $errors es una instancia de ViewErrorBag disponible en todas las vistas tras una validación fallida.' },
    { tema:'UF5', p:'¿Qué método del controlador devuelve una vista Blade con datos en Laravel?', ops:['return template("vista", $datos)','return render("vista", $datos)','return view("vista", compact("var1","var2"))','return blade("vista", $datos)'], r:2, e:'return view("nombre.vista", compact("variable")) o return view("nombre.vista", ["clave" => $valor]) devuelve una respuesta con la vista Blade renderizada.' },
    { tema:'UF5', p:'¿Qué helper compact() hace en Laravel?', ops:['Comprime archivos PHP','Crea un array asociativo con el nombre de las variables como clave y su valor, para pasar datos a las vistas','Fusiona dos arrays en uno','Elimina duplicados de un array'], r:1, e:'compact("var1", "var2") crea un array ["var1" => $var1, "var2" => $var2]. Es un atajo conveniente para pasar variables a las vistas con view().' },
    { tema:'UF5', p:'¿Qué hace redirect()->route("nombre") en un controlador Laravel?', ops:['Renderiza la vista asociada a esa ruta','Genera la URL de la ruta sin redirigir','Redirige el navegador del cliente a la URL de la ruta nombrada','Carga los datos del modelo de esa ruta'], r:2, e:'redirect()->route("nombre") genera una respuesta HTTP de redirección (302) al navegador, enviándolo a la URL de la ruta nombrada.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF6 — FRAMEWORKS PARA PHP II (Laravel ORM/Eloquent)
  // ─────────────────────────────────────────────────────────
  UF6: [
    { tema:'UF6', p:'¿Qué es Eloquent en Laravel?', ops:['El motor de plantillas de Laravel','El ORM (Object-Relational Mapping) de Laravel que permite interactuar con bases de datos usando objetos PHP en lugar de SQL','El cliente de línea de comandos de Laravel','El sistema de caché de Laravel'], r:1, e:'Eloquent es el ORM de Laravel. Mapea tablas de base de datos a modelos PHP, permitiendo realizar consultas complejas sin escribir SQL directamente.' },
    { tema:'UF6', p:'¿Qué es un ORM?', ops:['Un sistema de enrutamiento web','Object-Relational Mapping: una técnica que mapea objetos de código a registros de base de datos, abstrayendo el SQL','Un framework de testing para bases de datos','Un motor de plantillas para PHP'], r:1, e:'ORM (Object-Relational Mapping) permite trabajar con la base de datos usando objetos PHP en lugar de SQL puro. Cada tabla se representa como una clase (Modelo).' },
    { tema:'UF6', p:'¿Dónde se configuran los parámetros de conexión a la base de datos en Laravel?', ops:['En el archivo config/app.php','En el archivo .env y config/database.php','En el controlador de base de datos','En el archivo routes/database.php'], r:1, e:'Los parámetros de BD se definen en el archivo .env (DB_CONNECTION, DB_HOST, DB_DATABASE, DB_USERNAME, DB_PASSWORD) y se leen en config/database.php.' },
    { tema:'UF6', p:'¿Qué variable del archivo .env de Laravel define el tipo de SGBD a usar?', ops:['DB_TYPE','DB_DRIVER','DB_CONNECTION','DB_ENGINE'], r:2, e:'DB_CONNECTION define el SGBD: mysql, pgsql, sqlite, sqlsrv. Por defecto es mysql si no se especifica (ver config/database.php).' },
    { tema:'UF6', p:'¿Qué son las migraciones en Laravel?', ops:['Copias de seguridad de la base de datos','Un sistema de control de versiones para el esquema de la base de datos, que permite crear y modificar tablas con código PHP','Un sistema de importación de datos CSV','Procedimientos almacenados en la base de datos'], r:1, e:'Las migraciones son control de versiones del esquema de BD. Definen la estructura de tablas en código PHP, permitiendo a todo el equipo tener la misma estructura de BD.' },
    { tema:'UF6', p:'¿Qué dos métodos debe tener toda migración de Laravel?', ops:['create() y drop()','install() y uninstall()','up() y down()','apply() y revert()'], r:2, e:'up() aplica los cambios (crear/modificar tablas). down() revierte los cambios de up(). Esto permite ejecutar y deshacer migraciones.' },
    { tema:'UF6', p:'¿Qué comando ejecuta todas las migraciones pendientes en Laravel?', ops:['php artisan migrate:run','php artisan db:migrate','php artisan migrate','php artisan migration:up'], r:2, e:'php artisan migrate ejecuta los métodos up() de todas las migraciones pendientes (las que no están en la tabla migrations de la BD).' },
    { tema:'UF6', p:'¿Qué comando crea una nueva migración en Laravel?', ops:['php artisan create:migration nombre','php artisan new migration nombre','php artisan make:migration nombre','php artisan migration:create nombre'], r:2, e:'php artisan make:migration nombre_migración crea un nuevo archivo de migración con la fecha como prefijo en database/migrations/.' },
    { tema:'UF6', p:'¿Qué hace php artisan migrate:rollback?', ops:['Elimina todas las tablas de la base de datos','Revierte el último lote de migraciones ejecutando los métodos down()','Crea una copia de seguridad de la base de datos','Reinicia el servidor de base de datos'], r:1, e:'php artisan migrate:rollback revierte el último lote de migraciones ejecutando sus métodos down(). Se puede especificar cuántos pasos retroceder con --step=N.' },
    { tema:'UF6', p:'¿Qué comando de Laravel crea un modelo Eloquent?', ops:['php artisan new:model Nombre','php artisan generate:model Nombre','php artisan make:model Nombre','php artisan create:model Nombre'], r:2, e:'php artisan make:model Nombre crea un modelo en app/Models/. Con -m también crea la migración. Con -c crea el controlador. Con -mcr crea todo a la vez.' },
    { tema:'UF6', p:'¿Qué convención de nomenclatura usa Eloquent para asociar un modelo a una tabla?', ops:['El mismo nombre que la clase del modelo','El nombre de la clase en minúsculas y singular','El nombre de la clase en minúsculas, snake_case y plural','El nombre definido en el archivo de configuración'], r:2, e:'Eloquent asume que la tabla se llama igual que el modelo pero en minúsculas, snake_case y plural. Modelo "Producto" → tabla "productos". Se puede personalizar con $table.' },
    { tema:'UF6', p:'¿Cómo se obtienen todos los registros de una tabla con Eloquent?', ops:['Modelo::select("*")','Modelo::getAll()','Modelo::fetchAll()','Modelo::all()'], r:3, e:'Modelo::all() devuelve una Collection con todos los registros de la tabla correspondiente al modelo.' },
    { tema:'UF6', p:'¿Cómo se busca un registro por su clave primaria en Eloquent?', ops:['Modelo::get($id)','Modelo::find($id)','Modelo::where("id", $id)->first()','Modelo::findById($id)'], r:1, e:'Modelo::find($id) busca un registro por su clave primaria y devuelve una instancia del modelo o null si no existe. Equivalente a SELECT * WHERE id = $id.' },
    { tema:'UF6', p:'¿Qué método Eloquent añade una condición WHERE a la consulta?', ops:['Modelo::filter()','Modelo::condition()','Modelo::where()','Modelo::search()'], r:2, e:'Modelo::where("columna", "valor") o Modelo::where("columna", "operador", "valor") añade una condición WHERE. Se puede encadenar con ->get() para ejecutar.' },
    { tema:'UF6', p:'¿Cómo se inserta un nuevo registro con Eloquent usando mass assignment?', ops:['Modelo::add($datos)','Modelo::insert($datos)','Modelo::create($datos)','Modelo::new($datos)'], r:2, e:'Modelo::create($arrayDatos) crea y guarda un nuevo registro. Requiere que los campos estén en la propiedad $fillable del modelo (protección contra mass assignment).' },
    { tema:'UF6', p:'¿Para qué sirve la propiedad $fillable en un modelo Eloquent?', ops:['Para definir qué columnas se devuelven en las consultas','Para especificar qué campos pueden asignarse masivamente con create() o fill(), protegiendo contra mass assignment attacks','Para definir las relaciones del modelo','Para establecer los índices de la tabla'], r:1, e:'$fillable lista los campos que pueden ser asignados masivamente con Modelo::create() o $modelo->fill(). Sin ella, Eloquent lanza una excepción de MassAssignmentException.' },
    { tema:'UF6', p:'¿Cómo se actualiza un registro con Eloquent?', ops:['$modelo->modify($datos); $modelo->commit()','$modelo->update($datos)','$modelo->set($datos); $modelo->save()','Modelo::where("id",$id)->set($datos)'], r:1, e:'$instancia->update($datos) actualiza los campos del registro. También se puede hacer $instancia->campo = valor; $instancia->save().' },
    { tema:'UF6', p:'¿Cómo se elimina un registro con Eloquent?', ops:['$modelo->remove()','$modelo->delete()','Modelo::remove($id)','$modelo->drop()'], r:1, e:'$instancia->delete() elimina el registro de la base de datos. También se puede usar Modelo::destroy($id) o Modelo::destroy([$id1, $id2]).' },
    { tema:'UF6', p:'¿Qué son los seeders en Laravel?', ops:['Archivos de migración para crear tablas','Clases que rellenan la base de datos con datos de prueba o iniciales','Scripts para hacer copias de seguridad','Comandos para importar datos CSV'], r:1, e:'Los seeders son clases que insertan datos en la base de datos (datos de prueba, catálogos iniciales, etc.). Se ejecutan con php artisan db:seed.' },
    { tema:'UF6', p:'¿Qué relación Eloquent representa que un modelo pertenece a otro (clave foránea en la tabla actual)?', ops:['hasOne()','belongsToMany()','hasMany()','belongsTo()'], r:3, e:'belongsTo() indica que el modelo actual pertenece a otro. Implica que la tabla actual tiene la clave foránea. Ej: un Comentario belongsTo Post.' },
    { tema:'UF6', p:'¿Qué relación Eloquent indica que un modelo tiene muchos registros de otro modelo?', ops:['hasOne()','belongsTo()','hasMany()','manyToMany()'], r:2, e:'hasMany() indica que el modelo actual tiene muchos registros del otro modelo. Ej: un Post hasMany Comentarios. La clave foránea está en la tabla de comentarios.' },
    { tema:'UF6', p:'¿Qué comando de artisan revierte TODAS las migraciones y las vuelve a ejecutar?', ops:['php artisan migrate:reset','php artisan migrate:refresh','php artisan migrate:fresh','php artisan migrate:redo'], r:1, e:'php artisan migrate:refresh ejecuta todos los down() y luego todos los up(). Con --seed también ejecuta los seeders. migrate:fresh es más agresivo: borra las tablas directamente.' },
    { tema:'UF6', p:'¿Qué método Schema usa Eloquent para crear una tabla en una migración?', ops:['Schema::make()','Schema::build()','Schema::new()','Schema::create()'], r:3, e:'Schema::create("nombre_tabla", function(Blueprint $table) { ... }) crea una nueva tabla con la estructura definida en el closure.' },
    { tema:'UF6', p:'¿Qué tipo de campo Eloquent/Blueprint crea un entero autoincremental como clave primaria?', ops:['$table->integer("id")->primary()','$table->autoIncrement("id")','$table->id() o $table->increments("id")','$table->primaryKey("id")'], r:2, e:'$table->id() es el método moderno (Laravel 8+) para crear un campo BIGINT UNSIGNED autoincremental como clave primaria. El clásico es $table->increments("id") para INT.' },
    { tema:'UF6', p:'¿Qué hace $table->timestamps() en una migración de Laravel?', ops:['Añade solo el campo created_at','Añade solo el campo updated_at','Añade los campos created_at y updated_at que Laravel gestiona automáticamente','Añade un campo timestamp con la fecha actual'], r:2, e:'$table->timestamps() añade los campos created_at y updated_at. Laravel los gestiona automáticamente al insertar y actualizar registros a través de Eloquent.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF7 — SERVICIOS WEB REST
  // ─────────────────────────────────────────────────────────
  UF7: [
    { tema:'UF7', p:'¿Qué es una API REST?', ops:['Un servidor web especial para PHP','Un conjunto de principios arquitectónicos para servicios web que usa HTTP y permite operaciones CRUD mediante sus métodos','Un framework JavaScript para consumir servicios','Un protocolo de seguridad para aplicaciones web'], r:1, e:'REST (Representational State Transfer) es un estilo arquitectónico para servicios web que usa métodos HTTP (GET, POST, PUT, DELETE) para operaciones CRUD sobre recursos.' },
    { tema:'UF7', p:'¿Qué método HTTP se usa en REST para OBTENER recursos?', ops:['POST','PUT','GET','FETCH'], r:2, e:'GET se usa para recuperar recursos. Es idempotente (múltiples peticiones iguales producen el mismo resultado) y no debe modificar datos en el servidor.' },
    { tema:'UF7', p:'¿Qué método HTTP se usa en REST para CREAR un nuevo recurso?', ops:['PUT','PATCH','CREATE','POST'], r:3, e:'POST se usa para crear nuevos recursos. El servidor responde con 201 Created si el recurso se creó correctamente.' },
    { tema:'UF7', p:'¿Qué método HTTP se usa en REST para ACTUALIZAR completamente un recurso?', ops:['POST','PATCH','PUT','UPDATE'], r:2, e:'PUT reemplaza completamente un recurso. PATCH lo actualiza parcialmente. PUT es idempotente (el mismo resultado si se repite).' },
    { tema:'UF7', p:'¿Qué método HTTP se usa en REST para ELIMINAR un recurso?', ops:['REMOVE','POST','CLEAR','DELETE'], r:3, e:'DELETE elimina el recurso especificado. Responde con 204 No Content si se eliminó correctamente o 404 si el recurso no existía.' },
    { tema:'UF7', p:'¿Qué código de estado HTTP indica que un recurso fue creado correctamente?', ops:['200 OK','201 Created','204 No Content','202 Accepted'], r:1, e:'201 Created se devuelve cuando un recurso fue creado exitosamente (respuesta a POST). A menudo incluye la Location del nuevo recurso en las cabeceras.' },
    { tema:'UF7', p:'¿Qué código de estado HTTP indica que la petición fue exitosa pero no hay contenido que devolver?', ops:['200 OK','201 Created','204 No Content','202 Accepted'], r:2, e:'204 No Content indica éxito sin cuerpo de respuesta. Típico en operaciones DELETE o PUT que no devuelven datos.' },
    { tema:'UF7', p:'¿Qué código de estado HTTP indica que el cliente no está autenticado?', ops:['400','403','401','404'], r:2, e:'401 Unauthorized indica que la petición requiere autenticación. El cliente debe incluir credenciales válidas (token, sesión, etc.).' },
    { tema:'UF7', p:'¿Qué código de estado HTTP indica que el cliente está autenticado pero no tiene permisos?', ops:['401','404','403','500'], r:2, e:'403 Forbidden indica que el servidor entendió la petición y el usuario está autenticado, pero no tiene permiso para acceder al recurso.' },
    { tema:'UF7', p:'¿Qué formato de datos se usa habitualmente en las respuestas de APIs REST modernas?', ops:['XML','HTML','CSV','JSON'], r:3, e:'JSON es el formato estándar de facto para APIs REST. Es ligero, legible y nativamente soportado en JavaScript y prácticamente todos los lenguajes modernos.' },
    { tema:'UF7', p:'¿Qué es un controlador de API en Laravel?', ops:['Un controlador que solo genera vistas Blade','Un controlador orientado a responder con datos (JSON) en lugar de vistas HTML, para servir como API REST','Un controlador para gestionar la autenticación','Un middleware que protege las rutas de API'], r:1, e:'Los controladores de API en Laravel responden con JSON en lugar de vistas. Se crean con php artisan make:controller NombreController --api y tienen métodos index, store, show, update, destroy.' },
    { tema:'UF7', p:'¿Qué comando crea un controlador de API con métodos CRUD en Laravel?', ops:['php artisan make:controller NombreController --rest','php artisan make:controller NombreController --api','php artisan make:controller NombreController --crud','php artisan make:controller Api/NombreController --resource'], r:1, e:'php artisan make:controller NombreController --api crea un controlador con los métodos index, store, show, update y destroy (sin create y edit que son para vistas HTML).' },
    { tema:'UF7', p:'¿Qué diferencia hay entre un controlador --resource y uno --api en Laravel?', ops:['No hay diferencia','--resource incluye todos los métodos (create, edit para vistas); --api omite create() y edit() ya que no sirven vistas HTML','--api es más rápido','--resource solo para GET; --api para todos los métodos'], r:1, e:'--resource incluye los 7 métodos: index, create, store, show, edit, update, destroy. --api omite create() y edit() (que muestran formularios HTML, innecesarios en APIs).' },
    { tema:'UF7', p:'¿Qué helper de Laravel genera una respuesta JSON con código de estado en un controlador de API?', ops:['json($datos, $codigo)','JsonResponse::make($datos)','response()->json($datos, $codigo)','Json::return($datos)'], r:2, e:'response()->json($datos, $codigo) genera una respuesta JSON con el Content-Type application/json y el código de estado HTTP especificado.' },
    { tema:'UF7', p:'¿Dónde se definen las rutas de API en Laravel?', ops:['routes/web.php','routes/api.php','routes/rest.php','config/api.php'], r:1, e:'Las rutas de API se definen en routes/api.php. Estas rutas tienen el prefijo /api automáticamente y no usan sesiones ni cookies (stateless).' },
    { tema:'UF7', p:'¿Qué método Route::apiResource hace en Laravel?', ops:['Crea rutas solo para GET','Crea las 5 rutas REST estándar (index, store, show, update, destroy) para un controlador de API automáticamente','Crea las 7 rutas incluyendo create y edit','Crea solo las rutas POST y DELETE'], r:1, e:'Route::apiResource("recurso", Controlador::class) crea automáticamente las 5 rutas REST: GET (index/show), POST (store), PUT/PATCH (update), DELETE (destroy).' },
    { tema:'UF7', p:'¿Qué es la diferencia entre SOAP y REST?', ops:['No hay diferencia significativa','SOAP es un protocolo estricto basado en XML con estándares de seguridad; REST es un estilo arquitectónico más flexible que usa HTTP directamente','REST solo funciona con JSON; SOAP solo con XML','SOAP es más moderno que REST'], r:1, e:'SOAP es un protocolo rígido con XML, WS-Security, WSDL. REST es un estilo más flexible usando directamente HTTP. REST es más ligero y el predominante actualmente.' },
    { tema:'UF7', p:'¿Qué cabecera HTTP debe incluir una petición para indicar que envía datos JSON?', ops:['Accept: application/json','Content-Type: application/json','Data-Type: json','Format: json'], r:1, e:'Content-Type: application/json indica al servidor que el cuerpo de la petición está en formato JSON y debe interpretarse como tal.' },
    { tema:'UF7', p:'¿Qué cabecera HTTP indica al servidor que el cliente acepta respuestas en JSON?', ops:['Content-Type: application/json','Response-Format: json','Accept: application/json','Output: json'], r:2, e:'Accept: application/json indica al servidor que el cliente prefiere recibir la respuesta en formato JSON. El servidor usa esta cabecera para content negotiation.' },
    { tema:'UF7', p:'¿Qué son los Resource Controllers en Laravel?', ops:['Controladores que gestionan archivos estáticos','Controladores que implementan los métodos CRUD estándar siguiendo la convención RESTful de Laravel','Controladores para gestionar imágenes y videos','Controladores con acceso directo a la base de datos'], r:1, e:'Resource Controllers implementan los métodos CRUD de forma convencional: index (listar), create (formulario alta), store (guardar), show (ver), edit (editar), update (actualizar), destroy (eliminar).' },
    { tema:'UF7', p:'¿Qué código de estado HTTP indica un error interno del servidor?', ops:['400','403','404','500'], r:3, e:'500 Internal Server Error indica que el servidor encontró una condición inesperada que le impidió completar la petición. Es un error del lado del servidor, no del cliente.' },
    { tema:'UF7', p:'¿Qué significa que REST es "stateless" (sin estado)?', ops:['Que el servidor nunca guarda datos de los usuarios','Que cada petición HTTP debe contener toda la información necesaria; el servidor no guarda contexto de peticiones anteriores','Que no se pueden usar sesiones en ningún caso','Que la aplicación no puede usar base de datos'], r:1, e:'Stateless significa que cada petición es independiente y debe contener toda la información necesaria. El servidor no guarda estado entre peticiones, mejorando escalabilidad.' },
    { tema:'UF7', p:'¿Qué herramienta se usa habitualmente para probar APIs REST durante el desarrollo?', ops:['PhpStorm','Apache JMeter','Postman','MySQL Workbench'], r:2, e:'Postman es la herramienta más popular para probar APIs REST. Permite hacer peticiones HTTP con cualquier método, cabeceras, cuerpo JSON y ver las respuestas.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF8 — APLICACIONES WEB HÍBRIDAS (MASHUP)
  // ─────────────────────────────────────────────────────────
  UF8: [
    { tema:'UF8', p:'¿Qué es una aplicación web híbrida (mashup)?', ops:['Una aplicación que mezcla PHP y JavaScript en el mismo archivo','Una aplicación web que integra datos y servicios de fuentes externas (APIs, RSS, servicios web) para generar un nuevo servicio','Una aplicación que funciona tanto en móvil como en escritorio','Una aplicación que mezcla SQL y NoSQL'], r:1, e:'Un mashup es una aplicación web que combina datos o funcionalidades de múltiples fuentes externas (APIs, servicios web) para crear un nuevo servicio de valor añadido.' },
    { tema:'UF8', p:'¿Cuáles son las tres partes principales de la arquitectura de un mashup?', ops:['Frontend, Backend, Base de datos','Proveedor de contenidos, Servidor del mashup, Cliente web','Cliente, Proxy, Servidor','HTML, CSS, JavaScript'], r:1, e:'La arquitectura mashup tiene: Proveedor de contenidos (fuente de datos/API), Servidor del mashup (procesa y combina datos), Cliente web (interfaz del usuario).' },
    { tema:'UF8', p:'¿Qué es RSS en el contexto de aplicaciones web híbridas?', ops:['Un protocolo de seguridad para APIs','Really Simple Syndication: tecnología basada en XML que permite compartir y distribuir contenidos web de forma estandarizada','Un método de autenticación OAuth','Un formato de intercambio de datos alternativo a JSON'], r:1, e:'RSS (Really Simple Syndication) es un formato XML para sindicación web: permite que sitios web distribuyan sus contenidos (noticias, artículos) de forma estructurada y automatizada.' },
    { tema:'UF8', p:'¿Cuál es la principal diferencia entre RSS y Atom?', ops:['RSS es más reciente que Atom','Atom es un estándar IETF más completo y consistente que RSS; soporta más tipos de contenido, elementos summary/content separados e identificadores internacionales','RSS soporta más idiomas que Atom','Atom solo funciona con JSON; RSS con XML'], r:1, e:'Atom es estándar IETF, más completo: separa summary y content, soporta IRIs, especifica idioma por elemento, tiene cargas útiles más variadas. RSS es más popular pero menos estricto.' },
    { tema:'UF8', p:'¿Qué es el screen scraping o web scraping?', ops:['Una técnica para comprimir páginas web','Una técnica que extrae datos de páginas web analizando el HTML, usualmente mediante ingeniería inversa','Una forma de optimizar imágenes web','Un método de cifrado para comunicaciones HTTPS'], r:1, e:'Web scraping extrae información de páginas web analizando su HTML. Se usa cuando no existe API, pero tiene inconvenientes: legalidad, fragilidad ante cambios en la web y sobrecarga del servidor.' },
    { tema:'UF8', p:'¿Por qué el web scraping está en desuso según el temario?', ops:['Porque es demasiado lento','Por sus inconvenientes: no siempre está autorizado, complejidad, sobrecarga de servidores y propensión a fallos ante cambios en la web','Porque JSON lo ha reemplazado completamente','Porque viola siempre la privacidad'], r:1, e:'El scraping tiene múltiples problemas: no siempre lo autorizan los sitios, es complejo de implementar, sobrecarga los servidores origen y es frágil (cualquier cambio en el HTML lo rompe).' },
    { tema:'UF8', p:'¿Qué es AJAX en el contexto de aplicaciones web híbridas?', ops:['Un framework PHP para APIs','Asynchronous JavaScript and XML: técnica para hacer peticiones HTTP asíncronas desde el navegador sin recargar la página','Un protocolo de seguridad web','Un sistema de base de datos NoSQL'], r:1, e:'AJAX permite al navegador hacer peticiones HTTP al servidor en segundo plano (asíncronas) sin recargar la página completa, actualizando solo partes del DOM con los datos recibidos.' },
    { tema:'UF8', p:'¿Cuáles son las ventajas de usar una API para obtener datos en un mashup frente al scraping?', ops:['El scraping es siempre más rápido','La API ofrece fiabilidad, escalabilidad, flexibilidad, está documentada y el proveedor tiene servidores específicos con gestión de errores adecuada','No hay ventajas reales entre ambos','El scraping es más seguro que la API'], r:1, e:'Las APIs son fiables (estructura garantizada), escalables, flexibles, bien documentadas y con gestión de errores. El scraping depende del HTML que puede cambiar sin aviso.' },
    { tema:'UF8', p:'¿Qué significa que una aplicación incluya un vídeo de YouTube incrustado? ¿Es un mashup?', ops:['Sí, cualquier contenido externo hace que sea un mashup','No: para ser mashup, la aplicación debe acceder y procesar datos del servicio externo, no solo incrustar contenido estático','Solo si el vídeo se procesa con JavaScript','Depende del lenguaje de programación usado'], r:1, e:'Incrustar un vídeo de YouTube (iframe) NO es un mashup. Para serlo, la aplicación debe acceder a datos o procesar información a través del proveedor (como la API de YouTube).' },
    { tema:'UF8', p:'¿Qué protocolo usan los mashups para comunicarse con los proveedores de contenidos?', ops:['FTP','SMTP','HTTP/HTTPS','SSH'], r:2, e:'Los mashups usan HTTP/HTTPS para comunicarse con proveedores de contenidos. Los servicios se consumen mediante peticiones HTTP estándar.' },
    { tema:'UF8', p:'¿Qué es OAuth en el contexto de APIs y mashups?', ops:['Un formato de datos alternativo a JSON','Un protocolo de autorización estándar que permite a aplicaciones acceder a recursos de un usuario en otro servicio sin compartir contraseñas','Un protocolo de cifrado de datos','Un tipo de API REST especializado'], r:1, e:'OAuth es el protocolo estándar de autorización delegada. Permite que una aplicación acceda a recursos de un usuario en otro servicio (Twitter, Google) sin que el usuario comparta su contraseña.' },
    { tema:'UF8', p:'¿Qué es un webhook?', ops:['Una librería JavaScript para consumir APIs','Un mecanismo por el que un servicio externo envía datos automáticamente a nuestra aplicación cuando ocurre un evento, sin que tengamos que hacer polling','Una forma de scraping automatizado','Una API REST bidireccional'], r:1, e:'Un webhook es una URL de nuestra aplicación que registramos en un servicio externo. Cuando ocurre un evento (pago, mensaje), el servicio hace una petición POST a nuestra URL con los datos.' },
    { tema:'UF8', p:'¿Qué es el "mismo origen" (same-origin policy) y por qué afecta a los mashups?', ops:['Una política que limita el acceso a archivos locales desde el navegador','Una restricción del navegador que impide que JavaScript de un origen haga peticiones a otro dominio diferente; los mashups necesitan CORS o hacer las peticiones desde el servidor','Una política de seguridad de bases de datos','Una restricción que impide PHP acceder a APIs externas'], r:1, e:'Same-origin policy impide que JavaScript haga peticiones a dominios distintos. Los mashups lo resuelven con CORS (el servidor añade cabeceras) o haciendo las peticiones desde el servidor PHP.' },
    { tema:'UF8', p:'¿Qué significa CORS?', ops:['Content Origin Resource Sharing','Cross-Origin Resource Sharing: mecanismo que permite o restringe peticiones HTTP entre diferentes orígenes mediante cabeceras HTTP','Cross-Origin Request Security','Content Resource Sharing Standard'], r:1, e:'CORS (Cross-Origin Resource Sharing) son cabeceras HTTP (Access-Control-Allow-Origin) que el servidor incluye para permitir peticiones desde orígenes distintos al suyo.' },
  ],

  // ─────────────────────────────────────────────────────────
  // UF9 — SERVIDORES EN LA NUBE
  // ─────────────────────────────────────────────────────────
  UF9: [
    { tema:'UF9', p:'¿Qué es AWS EC2?', ops:['Un servicio de almacenamiento de objetos de Amazon','Elastic Compute Cloud: el servicio de virtualización de máquinas a gran escala de AWS, pionero del cloud computing','Un servicio de base de datos gestionada de Amazon','Un servicio de CDN de Amazon'], r:1, e:'EC2 (Elastic Compute Cloud) es el servicio de virtualización de máquinas de AWS. Es el servicio pionero del cloud computing (2006), que ofrece máquinas virtuales con control total.' },
    { tema:'UF9', p:'¿Qué es AWS S3?', ops:['Un servicio de base de datos SQL','Un servicio de computación sin servidor','Simple Storage Service: servicio de almacenamiento masivo de objetos de AWS','Un servicio de red virtual privada de AWS'], r:2, e:'S3 (Simple Storage Service) es el servicio de almacenamiento masivo de objetos de AWS. Permite almacenar y recuperar cualquier cantidad de datos desde cualquier lugar. Muy usado para archivos estáticos.' },
    { tema:'UF9', p:'¿Qué es el escalado vertical en el contexto de la nube?', ops:['Añadir más servidores iguales al sistema','Aumentar los recursos (CPU, RAM, disco) de una instancia existente sin añadir nuevas máquinas','Distribuir la carga entre múltiples servidores','Añadir más zonas geográficas al despliegue'], r:1, e:'Escalado vertical (scale up): aumentar los recursos de la misma instancia (más CPU, más RAM). Tiene límite máximo. Es más simple pero crea punto único de fallo.' },
    { tema:'UF9', p:'¿Qué es el escalado horizontal en la nube?', ops:['Aumentar los recursos de una sola instancia','Añadir más instancias iguales y distribuir la carga entre ellas mediante un balanceador','Expandir el almacenamiento de una instancia','Aumentar el ancho de banda de la red'], r:1, e:'Escalado horizontal (scale out): añadir más instancias y distribuir la carga con un balanceador. Más tolerante a fallos y sin límite teórico. Es la estrategia preferida en la nube.' },
    { tema:'UF9', p:'¿Qué es serverless (computación sin servidor)?', ops:['Que la aplicación no necesita código de servidor','Un modelo donde el proveedor cloud gestiona automáticamente la infraestructura; el desarrollador solo sube funciones que se ejecutan bajo demanda','Un servidor que no consume energía','Una arquitectura donde todo el código corre en el cliente'], r:1, e:'Serverless: el desarrollador sube funciones (ej: AWS Lambda) y el proveedor gestiona automáticamente la infraestructura, escalado y alta disponibilidad. Solo se paga por ejecución.' },
    { tema:'UF9', p:'¿Qué servicio de AWS corresponde a la computación serverless?', ops:['AWS EC2','AWS ECS','AWS Lambda','AWS EKS'], r:2, e:'AWS Lambda es el servicio serverless de AWS. Ejecuta código (funciones) en respuesta a eventos sin necesidad de gestionar servidores. Se paga por el número de ejecuciones y tiempo consumido.' },
    { tema:'UF9', p:'¿Qué es Kubernetes y para qué se usa en la nube?', ops:['Un sistema de almacenamiento en la nube','Un sistema de orquestación de contenedores que automatiza el despliegue, escalado y gestión de contenedores Docker','Un lenguaje de programación para la nube','Un tipo de base de datos NoSQL para microservicios'], r:1, e:'Kubernetes es el sistema de orquestación de contenedores de código abierto (creado por Google). Automatiza despliegue, escalado, balanceo de carga y recuperación de contenedores.' },
    { tema:'UF9', p:'¿Qué servicio de AWS usa Kubernetes para orquestación de contenedores?', ops:['AWS ECS','AWS ECR','AWS EKS','AWS EC2 Container'], r:2, e:'AWS EKS (Elastic Kubernetes Service) es el servicio gestionado de Kubernetes en AWS. AWS ECS usa el orquestador propio de Amazon (no Kubernetes).' },
    { tema:'UF9', p:'¿Qué son los microservicios?', ops:['Aplicaciones web muy pequeñas','Una arquitectura donde la aplicación se divide en servicios pequeños e independientes, cada uno con su propia responsabilidad, base de datos y despliegue','Servicios web de muy bajo nivel','Mini-servidores físicos para la nube'], r:1, e:'La arquitectura de microservicios divide la aplicación en servicios pequeños, autónomos e independientes. Cada microservicio tiene su responsabilidad, puede desplegarse y escalarse de forma independiente.' },
    { tema:'UF9', p:'¿Qué es la integración continua (CI) en el desarrollo de software?', ops:['Integrar manualmente el código una vez al mes','Una práctica donde los desarrolladores integran su código frecuentemente (varias veces al día), verificando automáticamente con tests que no se introducen errores','Un tipo de control de versiones','Un sistema de despliegue manual'], r:1, e:'CI (Continuous Integration): los desarrolladores integran código frecuentemente. Cada integración dispara un pipeline automático (tests, análisis) para detectar errores rápido.' },
    { tema:'UF9', p:'¿Qué diferencia la entrega continua (CD - Continuous Delivery) del despliegue continuo (Continuous Deployment)?', ops:['Son exactamente lo mismo','En CD la entrega a producción requiere aprobación manual; en Continuous Deployment el despliegue a producción es también automático','CD usa Docker; Continuous Deployment usa Kubernetes','CD es para entornos de pruebas; Continuous Deployment para producción'], r:1, e:'Continuous Delivery: el código está siempre listo para producción pero el despliegue se activa manualmente. Continuous Deployment: el despliegue a producción también es automático.' },
    { tema:'UF9', p:'¿Qué herramienta de CI/CD se menciona junto con GitHub en el temario de DWES?', ops:['Jenkins exclusivamente','GitHub Actions / GitLab CI / Jenkins (herramientas de integración y despliegue continuos)','Solo Jenkins','Solo CircleCI'], r:1, e:'El temario menciona herramientas de CI/CD como GitHub Actions, GitLab CI, Jenkins. Permiten automatizar el pipeline de integración, testing y despliegue al hacer push al repositorio.' },
    { tema:'UF9', p:'¿Qué ventaja tiene el escalado horizontal frente al vertical en la nube?', ops:['El escalado horizontal es siempre más barato','El escalado horizontal ofrece mayor tolerancia a fallos (si un servidor cae, los demás continúan) y no tiene límite práctico de capacidad','El escalado horizontal es más sencillo de implementar','El escalado horizontal consume menos energía'], r:1, e:'El escalado horizontal distribuye la carga entre múltiples instancias: si una cae, las otras continúan (alta disponibilidad). No tiene límite práctico y es el modelo preferido en cloud.' },
    { tema:'UF9', p:'¿Qué es un VPS (Virtual Private Server)?', ops:['Un servidor físico dedicado exclusivamente','Un servidor virtual que simula ser un servidor dedicado, con recursos garantizados, dentro de un servidor físico compartido','Una red privada virtual para conectar servidores','Un servicio de almacenamiento virtual'], r:1, e:'Un VPS es una partición virtual de un servidor físico que actúa como servidor dedicado. El usuario tiene acceso root, recursos garantizados y aislamiento del resto de usuarios del mismo servidor físico.' },
    { tema:'UF9', p:'¿Qué servicio de AWS corresponde a un VPS o PaaS sencillo?', ops:['AWS EC2','AWS Lambda','AWS Lightsail','AWS ECS'], r:2, e:'AWS Lightsail es el servicio de VPS/PaaS simplificado de AWS. Está orientado a desarrolladores que necesitan algo sencillo, con precio fijo y menos opciones de configuración que EC2.' },
    { tema:'UF9', p:'¿Qué es un balanceador de carga (load balancer) en la nube?', ops:['Un sistema que aumenta la velocidad de procesamiento de una instancia','Un componente que distribuye el tráfico entrante entre múltiples instancias del servidor para optimizar el uso de recursos y garantizar alta disponibilidad','Un sistema de caché de base de datos','Un firewall para aplicaciones web'], r:1, e:'El balanceador de carga distribuye las peticiones entre múltiples instancias. Si una instancia cae, el balanceador redirige el tráfico a las restantes, garantizando alta disponibilidad.' },
    { tema:'UF9', p:'¿Qué es un API Gateway en arquitecturas de microservicios?', ops:['Una base de datos para microservicios','Un punto de entrada único para los clientes que enruta las peticiones a los microservicios correspondientes, añadiendo autenticación, rate limiting y otras funcionalidades','Un servidor web especializado para PHP','Un balanceador de carga para base de datos'], r:1, e:'El API Gateway es el punto de entrada único de la arquitectura de microservicios. Gestiona la autenticación, autorización, rate limiting, logging y enruta las peticiones al microservicio correcto.' },
    { tema:'UF9', p:'¿Qué es Docker en el contexto del despliegue en la nube?', ops:['Un servidor web especializado para la nube','Una plataforma de contenedores que empaqueta aplicaciones con sus dependencias para garantizar que funcionan igual en cualquier entorno','Un sistema operativo para servidores cloud','Una herramienta de monitorización de aplicaciones'], r:1, e:'Docker empaqueta una aplicación y todas sus dependencias en un contenedor ligero que se ejecuta de forma idéntica en cualquier entorno (desarrollo, test, producción, nube).' },
    { tema:'UF9', p:'¿Cuál es la diferencia entre AWS ECS y AWS EKS?', ops:['ECS es para máquinas virtuales; EKS para contenedores','ECS usa el orquestador propietario de Amazon; EKS usa Kubernetes (open source) para orquestación de contenedores','ECS es más barato siempre','No hay diferencia práctica entre ambos'], r:1, e:'ECS (Elastic Container Service) usa el sistema de orquestación propio de Amazon. EKS (Elastic Kubernetes Service) usa Kubernetes, el estándar open source, para mayor portabilidad.' },
  ],

}; // fin BANCO
